// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: face-recognition/grpc/face_recognition.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecognizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_face_recognition_grpc_face_recognition_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type RecognizedPerson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizedPerson) Reset() {
	*x = RecognizedPerson{}
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizedPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizedPerson) ProtoMessage() {}

func (x *RecognizedPerson) ProtoReflect() protoreflect.Message {
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizedPerson.ProtoReflect.Descriptor instead.
func (*RecognizedPerson) Descriptor() ([]byte, []int) {
	return file_face_recognition_grpc_face_recognition_proto_rawDescGZIP(), []int{1}
}

func (x *RecognizedPerson) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RecognizedPerson) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type RecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       []*RecognizedPerson    `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_face_recognition_grpc_face_recognition_proto_rawDescGZIP(), []int{2}
}

func (x *RecognizeResponse) GetPersons() []*RecognizedPerson {
	if x != nil {
		return x.Persons
	}
	return nil
}

type SubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectRequest) Reset() {
	*x = SubjectRequest{}
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectRequest) ProtoMessage() {}

func (x *SubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectRequest.ProtoReflect.Descriptor instead.
func (*SubjectRequest) Descriptor() ([]byte, []int) {
	return file_face_recognition_grpc_face_recognition_proto_rawDescGZIP(), []int{3}
}

func (x *SubjectRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SubjectFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Filenames     []string               `protobuf:"bytes,2,rep,name=filenames,proto3" json:"filenames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectFilesResponse) Reset() {
	*x = SubjectFilesResponse{}
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectFilesResponse) ProtoMessage() {}

func (x *SubjectFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_face_recognition_grpc_face_recognition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectFilesResponse.ProtoReflect.Descriptor instead.
func (*SubjectFilesResponse) Descriptor() ([]byte, []int) {
	return file_face_recognition_grpc_face_recognition_proto_rawDescGZIP(), []int{4}
}

func (x *SubjectFilesResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectFilesResponse) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

var File_face_recognition_grpc_face_recognition_proto protoreflect.FileDescriptor

const file_face_recognition_grpc_face_recognition_proto_rawDesc = "" +
	"\n" +
	",face-recognition/grpc/face_recognition.proto\x12\x0ffacerecognition\"/\n" +
	"\x10RecognizeRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"I\n" +
	"\x10RecognizedPerson\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"P\n" +
	"\x11RecognizeResponse\x12;\n" +
	"\apersons\x18\x01 \x03(\v2!.facerecognition.RecognizedPersonR\apersons\"*\n" +
	"\x0eSubjectRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"N\n" +
	"\x14SubjectFilesResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1c\n" +
	"\tfilenames\x18\x02 \x03(\tR\tfilenames2\xa9\x02\n" +
	"\x16FaceRecognitionService\x12W\n" +
	"\x0eRecognizeImage\x12!.facerecognition.RecognizeRequest\x1a\".facerecognition.RecognizeResponse\x12Y\n" +
	"\x0fGetSubjectFiles\x12\x1f.facerecognition.SubjectRequest\x1a%.facerecognition.SubjectFilesResponse\x12[\n" +
	"\x0eRecognizeBatch\x12!.facerecognition.RecognizeRequest\x1a\".facerecognition.RecognizeResponse(\x010\x01B!Z\x1fmyproject/face-recognition/grpcb\x06proto3"

var (
	file_face_recognition_grpc_face_recognition_proto_rawDescOnce sync.Once
	file_face_recognition_grpc_face_recognition_proto_rawDescData []byte
)

func file_face_recognition_grpc_face_recognition_proto_rawDescGZIP() []byte {
	file_face_recognition_grpc_face_recognition_proto_rawDescOnce.Do(func() {
		file_face_recognition_grpc_face_recognition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_face_recognition_grpc_face_recognition_proto_rawDesc), len(file_face_recognition_grpc_face_recognition_proto_rawDesc)))
	})
	return file_face_recognition_grpc_face_recognition_proto_rawDescData
}

var file_face_recognition_grpc_face_recognition_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_face_recognition_grpc_face_recognition_proto_goTypes = []any{
	(*RecognizeRequest)(nil),     // 0: facerecognition.RecognizeRequest
	(*RecognizedPerson)(nil),     // 1: facerecognition.RecognizedPerson
	(*RecognizeResponse)(nil),    // 2: facerecognition.RecognizeResponse
	(*SubjectRequest)(nil),       // 3: facerecognition.SubjectRequest
	(*SubjectFilesResponse)(nil), // 4: facerecognition.SubjectFilesResponse
}
var file_face_recognition_grpc_face_recognition_proto_depIdxs = []int32{
	1, // 0: facerecognition.RecognizeResponse.persons:type_name -> facerecognition.RecognizedPerson
	0, // 1: facerecognition.FaceRecognitionService.RecognizeImage:input_type -> facerecognition.RecognizeRequest
	3, // 2: facerecognition.FaceRecognitionService.GetSubjectFiles:input_type -> facerecognition.SubjectRequest
	0, // 3: facerecognition.FaceRecognitionService.RecognizeBatch:input_type -> facerecognition.RecognizeRequest
	2, // 4: facerecognition.FaceRecognitionService.RecognizeImage:output_type -> facerecognition.RecognizeResponse
	4, // 5: facerecognition.FaceRecognitionService.GetSubjectFiles:output_type -> facerecognition.SubjectFilesResponse
	2, // 6: facerecognition.FaceRecognitionService.RecognizeBatch:output_type -> facerecognition.RecognizeResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_face_recognition_grpc_face_recognition_proto_init() }
func file_face_recognition_grpc_face_recognition_proto_init() {
	if File_face_recognition_grpc_face_recognition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_face_recognition_grpc_face_recognition_proto_rawDesc), len(file_face_recognition_grpc_face_recognition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_face_recognition_grpc_face_recognition_proto_goTypes,
		DependencyIndexes: file_face_recognition_grpc_face_recognition_proto_depIdxs,
		MessageInfos:      file_face_recognition_grpc_face_recognition_proto_msgTypes,
	}.Build()
	File_face_recognition_grpc_face_recognition_proto = out.File
	file_face_recognition_grpc_face_recognition_proto_goTypes = nil
	file_face_recognition_grpc_face_recognition_proto_depIdxs = nil
}
