// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: face-recognition/grpc/face_recognition.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceRecognitionService_RecognizeImage_FullMethodName  = "/facerecognition.FaceRecognitionService/RecognizeImage"
	FaceRecognitionService_GetSubjectFiles_FullMethodName = "/facerecognition.FaceRecognitionService/GetSubjectFiles"
	FaceRecognitionService_RecognizeBatch_FullMethodName  = "/facerecognition.FaceRecognitionService/RecognizeBatch"
)

// FaceRecognitionServiceClient is the client API for FaceRecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceRecognitionServiceClient interface {
	// Unary: recognize faces in a single image and store results
	RecognizeImage(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	// Unary: get all file names linked to a subject
	GetSubjectFiles(ctx context.Context, in *SubjectRequest, opts ...grpc.CallOption) (*SubjectFilesResponse, error)
	// Bidirectional streaming: client streams image paths, server streams results back as each is processed
	RecognizeBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse], error)
}

type faceRecognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceRecognitionServiceClient(cc grpc.ClientConnInterface) FaceRecognitionServiceClient {
	return &faceRecognitionServiceClient{cc}
}

func (c *faceRecognitionServiceClient) RecognizeImage(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_RecognizeImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) GetSubjectFiles(ctx context.Context, in *SubjectRequest, opts ...grpc.CallOption) (*SubjectFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectFilesResponse)
	err := c.cc.Invoke(ctx, FaceRecognitionService_GetSubjectFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) RecognizeBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FaceRecognitionService_ServiceDesc.Streams[0], FaceRecognitionService_RecognizeBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecognizeRequest, RecognizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceRecognitionService_RecognizeBatchClient = grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse]

// FaceRecognitionServiceServer is the server API for FaceRecognitionService service.
// All implementations must embed UnimplementedFaceRecognitionServiceServer
// for forward compatibility.
type FaceRecognitionServiceServer interface {
	// Unary: recognize faces in a single image and store results
	RecognizeImage(context.Context, *RecognizeRequest) (*RecognizeResponse, error)
	// Unary: get all file names linked to a subject
	GetSubjectFiles(context.Context, *SubjectRequest) (*SubjectFilesResponse, error)
	// Bidirectional streaming: client streams image paths, server streams results back as each is processed
	RecognizeBatch(grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]) error
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

// UnimplementedFaceRecognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceRecognitionServiceServer struct{}

func (UnimplementedFaceRecognitionServiceServer) RecognizeImage(context.Context, *RecognizeRequest) (*RecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecognizeImage not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) GetSubjectFiles(context.Context, *SubjectRequest) (*SubjectFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubjectFiles not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) RecognizeBatch(grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]) error {
	return status.Error(codes.Unimplemented, "method RecognizeBatch not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) mustEmbedUnimplementedFaceRecognitionServiceServer() {
}
func (UnimplementedFaceRecognitionServiceServer) testEmbeddedByValue() {}

// UnsafeFaceRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceRecognitionServiceServer will
// result in compilation errors.
type UnsafeFaceRecognitionServiceServer interface {
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

func RegisterFaceRecognitionServiceServer(s grpc.ServiceRegistrar, srv FaceRecognitionServiceServer) {
	// If the following call panics, it indicates UnimplementedFaceRecognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceRecognitionService_ServiceDesc, srv)
}

func _FaceRecognitionService_RecognizeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).RecognizeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_RecognizeImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).RecognizeImage(ctx, req.(*RecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_GetSubjectFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).GetSubjectFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_GetSubjectFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).GetSubjectFiles(ctx, req.(*SubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_RecognizeBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FaceRecognitionServiceServer).RecognizeBatch(&grpc.GenericServerStream[RecognizeRequest, RecognizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceRecognitionService_RecognizeBatchServer = grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]

// FaceRecognitionService_ServiceDesc is the grpc.ServiceDesc for FaceRecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceRecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facerecognition.FaceRecognitionService",
	HandlerType: (*FaceRecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecognizeImage",
			Handler:    _FaceRecognitionService_RecognizeImage_Handler,
		},
		{
			MethodName: "GetSubjectFiles",
			Handler:    _FaceRecognitionService_GetSubjectFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecognizeBatch",
			Handler:       _FaceRecognitionService_RecognizeBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "face-recognition/grpc/face_recognition.proto",
}
