// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: person.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceRecognitionService_AddPerson_FullMethodName       = "/person.FaceRecognitionService/AddPerson"
	FaceRecognitionService_GetPersonByName_FullMethodName = "/person.FaceRecognitionService/GetPersonByName"
)

// FaceRecognitionServiceClient is the client API for FaceRecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceRecognitionServiceClient interface {
	AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
	GetPersonByName(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*Person, error)
}

type faceRecognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceRecognitionServiceClient(cc grpc.ClientConnInterface) FaceRecognitionServiceClient {
	return &faceRecognitionServiceClient{cc}
}

func (c *faceRecognitionServiceClient) AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Person)
	err := c.cc.Invoke(ctx, FaceRecognitionService_AddPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionServiceClient) GetPersonByName(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*Person, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Person)
	err := c.cc.Invoke(ctx, FaceRecognitionService_GetPersonByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceRecognitionServiceServer is the server API for FaceRecognitionService service.
// All implementations must embed UnimplementedFaceRecognitionServiceServer
// for forward compatibility.
type FaceRecognitionServiceServer interface {
	AddPerson(context.Context, *Person) (*Person, error)
	GetPersonByName(context.Context, *NameRequest) (*Person, error)
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

// UnimplementedFaceRecognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceRecognitionServiceServer struct{}

func (UnimplementedFaceRecognitionServiceServer) AddPerson(context.Context, *Person) (*Person, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPerson not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) GetPersonByName(context.Context, *NameRequest) (*Person, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersonByName not implemented")
}
func (UnimplementedFaceRecognitionServiceServer) mustEmbedUnimplementedFaceRecognitionServiceServer() {
}
func (UnimplementedFaceRecognitionServiceServer) testEmbeddedByValue() {}

// UnsafeFaceRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceRecognitionServiceServer will
// result in compilation errors.
type UnsafeFaceRecognitionServiceServer interface {
	mustEmbedUnimplementedFaceRecognitionServiceServer()
}

func RegisterFaceRecognitionServiceServer(s grpc.ServiceRegistrar, srv FaceRecognitionServiceServer) {
	// If the following call panics, it indicates UnimplementedFaceRecognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceRecognitionService_ServiceDesc, srv)
}

func _FaceRecognitionService_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_AddPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).AddPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognitionService_GetPersonByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServiceServer).GetPersonByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognitionService_GetPersonByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServiceServer).GetPersonByName(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceRecognitionService_ServiceDesc is the grpc.ServiceDesc for FaceRecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceRecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "person.FaceRecognitionService",
	HandlerType: (*FaceRecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _FaceRecognitionService_AddPerson_Handler,
		},
		{
			MethodName: "GetPersonByName",
			Handler:    _FaceRecognitionService_GetPersonByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
